namespace CircleDI.Blazor.Defenitions;

public static partial class Attributes {
    public const string ComponentModuleAttribute = $$"""
        // <auto-generated/>
        #pragma warning disable
        #nullable enable annotations


        #if !CIRCLEDI_EXCLUDE_ATTRIBUTES

        using System;

        namespace CircleDIAttributes;


        /// <summary>
        /// <para>
        /// This attribute is for cross project razor components importing.<br />
        /// A module decorated with this attribute gets an <see cref="TransientAttribute{TService}"/> for each class derived from <see cref="Microsoft.AspNetCore.Components.ComponentBase"/>.
        /// </para>
        /// <para>The module must be partial.</para>
        /// </summary>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Interface)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class ComponentModuleAttribute : Attribute;

        #endif

        """;
}
