namespace CircleDI.Defenitions;

public static partial class Attributes {
    public const string GetAccessEnum = $$"""
        // <auto-generated/>
        #pragma warning disable
        #nullable enable annotations


        #if !CIRCLEDI_EXCLUDE_ATTRIBUTES
        
        namespace CircleDIAttributes;

        /// <summary>
        /// The type of the member to access the service.<br />
        /// It can be either property or method.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal enum GetAccess {
            /// <summary>
            /// <para>The member will be a property with a get-accessor.</para>
            /// <para>The name of the property will be the same as the service name.</para>
            /// </summary>
            Property,

            /// <summary>
            /// <para>The member will be a method with no parameters.</para>
            /// <para>
            /// The name will be prefixed with "Get"<br />
            /// e.g. name "MyService" will generate member "GetMyService()".
            /// </para>
            /// </summary>
            Method
        }

        #endif

        """;
}
