namespace CircleDI.Defenitions;

public static partial class Attributes {
    public const string CreationTimingEnum = $$"""
        // <auto-generated/>
        #pragma warning disable
        #nullable enable annotations


        #if !CIRCLEDI_EXCLUDE_ATTRIBUTES

        namespace CircleDIAttributes;

        /// <summary>
        /// Configuration when the instantiation of the service happens.<br />
        /// At ServiceProvider instantiation (inside the constructor) or lazy (first time used).
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal enum CreationTiming {
            /// <summary>
            /// The instantiation of the service happens inside the constructor of the ServiceProvider.
            /// </summary>
            Constructor,

            /// <summary>
            /// The instantiation of the service happens the first time it is requested.
            /// </summary>
            Lazy
        }

        #endif

        """;
}
