namespace CircleDI;

public static partial class Attributes {
    public const string DependencyAttribute = $$"""
        // <auto-generated/>
        #pragma warning disable
        #nullable enable annotations


        #if !CIRCLEDI_EXCLUDE_ATTRIBUTES
        
        using System;
    
        namespace CircleDIAttributes;

        /// <summary>
        /// <para>This attribute is used to set a non-required property as dependency (required properties are always dependencies).</para>
        /// <para>It is also used to specify specific/named services, see <see cref="Name"/>.</para>
        /// </summary>
        [AttributeUsage(AttributeTargets.Property | AttributeTargets.Parameter)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class DependencyAttribute : Attribute {
            {{DEPENDENCY_NAME_PROPERTY}}
        }

        #endif

        """;
}
